# Config file for automatic testing at travis-ci.org

language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/import

env:
  - TOX_ENV=py27-dj18-coveralls
  - TOX_ENV=py34-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py27-dj110
  - TOX_ENV=py27-dj111
  - TOX_ENV=py34-dj19
  - TOX_ENV=py34-dj110
  - TOX_ENV=py34-dj111
  - TOX_ENV=py27-djmaster
  - TOX_ENV=py34-djmaster

matrix:
  allow_failures:
    - env: TOX_ENV=py27-djmaster
    - env: TOX_ENV=py34-djmaster

before_install:
  - pip install tox

# command to run tests using coverage, e.g. python setup.py test
script: CACHE_DIR=$HOME/.cache/import tox -e $TOX_ENV
