# Config file for automatic testing at travis-ci.org

language: python

env:
  - TOX_ENV=py27-dj17
  - TOX_ENV=py34-dj17
  - TOX_ENV=py27-dj18-coveralls
  - TOX_ENV=py34-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py34-dj19
  - TOX_ENV=py27-djmaster
  - TOX_ENV=py34-djmaster

matrix:
  allow_failures:
    - env: TOX_ENV=py27-djmaster
    - env: TOX_ENV=py34-djmaster

before_install:
  - pip install tox

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV
