name: Python package

on: [push, pull_request]

jobs:
  django:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python: 
          - 3.6
          - 3.7
          - 2.7
        django:
          - "==1.11.*"
          - "==2.1.*"
          - "==2.2.*"
        exclude:
          - python: 2.7
            django: "==2.1.*"
          - python: 2.7
            django: "==2.2.*"

    steps:
    - uses: actions/checkout@v1
    - name: Build application
      run: make build
      env:
        PYTHON_VERSION: ${{ matrix.python }}
        DJANGO_VERSION: ${{ matrix.django }}
    - name: Lint
      run: make lint
    - name: Migration check
      run: make check
    - name: Show settings
      run: make settings

    - name: Build test
      run: make test

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build application
      run: make build
    - name: Build documentation
      run: make docs